### PR TITLE
Replace null TURN server un/pw with empty strings

### PR DESCRIPTION
**Pull request by robertcrabtree**

### CODE REVIEW

**Comment by robertcrabtree** [comment]
I'll cut a new CocoaPod version if this looks okay.

**Comment by chadxz** [comment]
I am missing context for this change. What problem is it solving?

**Comment by chadxz** [comment]
Nevermind, I found the corresponding ticket in JIRA: MER-4430. 

"If a customer has not enabled TURN for their application in the developer console, the IOS SDK will crash when it attempts to start a call. In this situation, the response from /v1/turn contains a single stun entry which does not have a username or password associated with it. The SDK then attempts to create a object using null values for the un/pw. This causes a crash."

**Comment by chadxz** [comment]
LGTM :+1:

It's kind of difficult to test this using the ios sample app. Production mode tokens can't simply be pasted into the input field because the TTL for them is very short, like 20 seconds i think. In order to reasonably test it the sample app would need to be modified to perform brokered auth. Unfortunately this is an anti-pattern, as you don't want to embed your app-secret into a client application. Having the sample app rely on a server to provide a brokered auth token though is kind of a high barrier to test it out in production mode, though. So i dunno.

Maybe the right answer to allow the sample app to be used in production mode would be to just have a flag in the source that indicates that the application is a devMode app, and when it is not, it performs a get request on a url to retrieve the token to use to connect, much like a real-world app would be implemented.

**Comment by robertcrabtree** [comment]
I modified the demo app and was able to verify that this patch does indeed fix the crash.

**Pull request merged**
